name: CI

on:
  push:
  pull_request:

jobs:
  PHPUnit:
    name: PHPUnit (PHP ${{ matrix.php }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'windows-2022' }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
        php:
          - 8.4
          - 8.3
          - 8.2
          - 8.1
          - 8.0
          - 7.4
          - 7.3
          - 7.2
          - 7.1
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: ${{ (matrix.os != 'windows-2022' || matrix.php < 8.1) && 'xdebug' || '' }} # temporarily skip Xdebug on Windows with PHP 8.1+ due to segfault with Xdebug 3.4.2
          ini-file: development
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text
        if: ${{ matrix.php >= 7.3 }}
      - run: vendor/bin/phpunit --coverage-text -c phpunit.xml.legacy
        if: ${{ matrix.php < 7.3 }}

  PHPUnit-macOS:
    name: PHPUnit (macOS)
    runs-on: macos-14
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: xdebug-3.4.1 # temporarily downgrade Xdebug due to segfault on macOS with Xdebug 3.4.2
          coverage: xdebug
      - run: composer install
      - run: vendor/bin/phpunit --coverage-text
